// Copyright 2026 Alan Ninan Thomas
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.
namespace Caliper.Core.Models;

/// <summary>
/// One row of the roadmap §3.4 durable-execution <c>runs</c> table — see
/// <see cref="Caliper.Core.Abstractions.IRunStore"/> for which runs are tracked.
/// </summary>
/// <param name="RunId">Generated by <c>IRunStore.StartAsync</c>; opaque, GUID-shaped.</param>
/// <param name="SessionId">The session this run drove.</param>
/// <param name="JobName"><c>RunSpec.JobName</c> for a scheduler/`/schedule run` run; null otherwise.</param>
/// <param name="Status">Coarse lifecycle status.</param>
/// <param name="Reason">
/// The terminal <c>CompletionReason</c> (as text) or error message for a completed/failed/cancelled
/// row; a startup-sweep note for an interrupted row; null while <see cref="RunStatus.Running"/>.
/// </param>
/// <param name="Step">The last <c>TurnStarted</c> step number observed, 0 before the first turn.</param>
/// <param name="MaxSteps">
/// The step budget in effect for the *current* leg of this run — the original
/// <c>RunSpec.MaxSteps ?? CaliperOptions.MaxSteps</c> at start, or the remaining budget after a
/// resume (<see cref="Caliper.Core.Agents.ConversationOrchestrator.ResumeAsync"/>). Used to compute
/// the next resume's remaining budget (<c>MaxSteps - Step</c>, floored at 1).
/// </param>
/// <param name="Unattended"><c>RunSpec.Unattended</c> at the time this run (or its current leg) started.</param>
/// <param name="StartedAt">When this run row was first created (not reset by a resume).</param>
/// <param name="UpdatedAt">When this row last changed (step bump, resume, or terminal write).</param>
public sealed record RunRecord(
    string RunId,
    string SessionId,
    string? JobName,
    RunStatus Status,
    string? Reason,
    int Step,
    int MaxSteps,
    bool Unattended,
    DateTimeOffset StartedAt,
    DateTimeOffset UpdatedAt);
